name: Get Citation Data

on: 
 workflow_dispatch:
 page_build: 
 schedule:
  - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Requirements
      run: |
        pip install -r google_scholar_crawler/requirements.txt
    - name: Run Crawler
      run: |
        cd ./google_scholar_crawler
        python main.py
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
    - name: Push Results
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add google_scholar_crawler/results/*.json
        git diff --staged --quiet || git commit -m "Updated Citation Data"
        git push origin HEAD:google-scholar-stats --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}